Math: Math.jack
	cp Math.jack MathTest
	../../tools/JackCompiler.sh MathTest

String: String.jack
	cp String.jack StringTest
	../../tools/JackCompiler.sh StringTest

Memory: Memory.jack
	cp Memory.jack MemoryTest
	../../tools/JackCompiler.sh MemoryTest
	cp Memory.jack MemoryTest/MemoryDiag
	../../tools/JackCompiler.sh MemoryTest/MemoryDiag

Array: Array.jack
	cp Array.jack ArrayTest
	../../tools/JackCompiler.sh ArrayTest

Screen: Screen.jack
	cp Screen.jack ScreenTest
	../../tools/JackCompiler.sh ScreenTest

Output: Output.jack
	cp Output.jack OutputTest
	../../tools/JackCompiler.sh OutputTest

clean:
	rm -rf `fd -e .vm`