Math:
	cp Math.jack MathTest
	../../tools/JackCompiler.sh MathTest

String:
	cp String.jack StringTest
	../../tools/JackCompiler.sh StringTest

Memory:
	cp Memory.jack MemoryTest
	../../tools/JackCompiler.sh MemoryTest
	cp Memory.jack MemoryTest/MemoryDiag
	../../tools/JackCompiler.sh MemoryTest/MemoryDiag

Array:
	cp Array.jack ArrayTest
	../../tools/JackCompiler.sh ArrayTest

clean:
	rm -rf `fd -e .vm`